### PR TITLE
Solve "Does not run in Docker anymore" #2

### PR DESCRIPTION
**Pull request by Lukires**
I don't know if this is the best approach, but removing `@auth.login_required` from
```python
@app.route("/repl", methods=["POST"])
@auth.login_required
def repl():
```
and instead just manually checking the token as such:
```python
@app.route("/repl", methods=["POST"])
def repl():
    authorization = request.headers.get("Authorization")
    if authorization is None:
        return auth_error(401)
    token = authorization[7:]
    if not verify_token(token):
        return auth_error(401)
    
```
seems to work for me without any issues.

### CODE REVIEW

**Comment by athas** [comment]
Your email implied that this is somehow bad.  Why is this bad?  There are no real security considerations here - even if it would be possible to hijack someone's session... why would you?

**Comment by Lukires** [comment]
I don't think it is a bad solution. I just am not entirely sure how the original code worked, and am therefore not completely sure of the implications of my changes.

But based on what I think, and my tests, I think it is fine.

**Comment by WilliamDue** [comment]
This should not break any of the other code, it may be the case that [ `@auth.login_required`](https://github.com/miguelgrinberg/Flask-HTTPAuth/blob/main/src/flask_httpauth.py#LL141-L179) does something more fancy or more securely then just this if statement but I have not looked much into it.

Also Lukires code is working for me inside the docker and so does the latest commit on the [main branch](https://github.com/diku-dk/futhark-repl/commit/dac0c3125c1bc7d3032cd534ae0be99f29173468).

**Comment by WilliamDue** [comment]
I also ran into the problem of the website inside Docker would say there were no more sessions but I have today tried installing Docker from [somewhere else](https://askubuntu.com/a/1437897) and (docker-desktop but I do not know if this also made a difference) which for some reason works.

**Pull request merged**
